services:
  postgres:
    image: postgres:17
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
  redis:
    image: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASS}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_PASS}
    ports:
      - "6379:6379"
  backend:
    build: backend
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - TEST_DB_USER=${TEST_DB_USER}
      - TEST_DB_PASS=${TEST_DB_PASS}
      - TEST_DB_HOST=${TEST_DB_HOST}
      - TEST_DB_PORT=${TEST_DB_PORT}
      - TEST_DB_NAME=${TEST_DB_NAME}
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASS=${REDIS_PASS}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_NAME=${REDIS_NAME}
      - TEST_REDIS_HOST=${TEST_REDIS_HOST}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_SECRET=${JWT_SECRET}
      - ACCESS_TOKEN_EXPIRE_SECONDS=${ACCESS_TOKEN_EXPIRE_SECONDS}
      - REFRESH_TOKEN_EXPIRE_SECONDS=${REFRESH_TOKEN_EXPIRE_SECONDS}
    ports:
      - "8000:8000"
    volumes:
      - "./backend:/app/"
    depends_on:
      - postgres